language: R
  before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
repos:
  CRAN: http://cran.rstudio.com
addons:
  apt:
    packages:
    - tcl8.5-dev
    - tk8.5-dev
r:
  - oldrel
  - release
  - devel
